import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Terms & Conditions — Basecamp',
    description: 'Terms and Conditions for using the Basecamp AI assistant.',
};

export default function TermsPage() {
    return (
        <div className="legal-page">
            <div className="legal-inner">
                <Link href="/" className="legal-back">← Back to Basecamp</Link>

                <div className="legal-draft-banner">
                    DRAFT — pending legal review. This copy is a placeholder and is not legal advice.
                </div>

                <h1>Terms &amp; Conditions</h1>
                <p className="legal-updated">Last updated: July 27, 2026</p>

                <h2>1. Acceptance of terms</h2>
                <p>
                    By accessing or using Basecamp (the &ldquo;Service&rdquo;), you agree to be bound by these
                    Terms &amp; Conditions. If you do not agree, do not use the Service.
                </p>

                <h2>2. The Service</h2>
                <p>
                    Basecamp is a general-purpose AI assistant. Responses are generated by large language
                    models and may be inaccurate, incomplete, or out of date. You are responsible for
                    independently verifying any information before relying on it. The Service is provided
                    &ldquo;as is&rdquo; without warranties of any kind.
                </p>

                <h2>3. Acceptable use</h2>
                <p>You agree not to use the Service to:</p>
                <ul>
                    <li>Submit or attempt to inject malicious code, scripts, or markup (including HTML,
                        JavaScript, or other executable content) into the Service or other users&rsquo; sessions.</li>
                    <li>Circumvent, probe, or test the vulnerability of the Service or its security controls.</li>
                    <li>Generate content that is unlawful, harmful, harassing, or infringes the rights of others.</li>
                    <li>Use automated means to access the Service in a manner that degrades it for others.</li>
                </ul>
                <p>
                    Inputs are screened for script/injection payloads and may be blocked. We may suspend or
                    terminate access for violations.
                </p>

                <h2>4. Subscriptions &amp; payment</h2>
                <p>
                    Pro features require an active subscription paid in cUSD on the Celo network. Subscriptions
                    are charged per the price shown at checkout and grant access for the stated period.
                    Blockchain transactions are irreversible; we do not control the network and cannot reverse
                    confirmed on-chain payments. Access ends when the subscription period expires unless renewed.
                </p>

                <h2>5. No professional advice</h2>
                <p>
                    Output does not constitute legal, financial, medical, or other professional advice.
                </p>

                <h2>6. Limitation of liability</h2>
                <p>
                    To the maximum extent permitted by law, we are not liable for any indirect, incidental, or
                    consequential damages arising from your use of the Service.
                </p>

                <h2>7. Changes</h2>
                <p>
                    We may update these terms. Continued use after changes constitutes acceptance.
                </p>

                <p className="legal-footer-note">
                    See also our <Link href="/privacy">Privacy Policy</Link>.
                </p>
            </div>
        </div>
    );
}
